<a href="https://colab.research.google.com/github/Shiv2183/NLP/blob/main/NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NLP

The objective is:
1. Understand the basic NLP algorithms
2. Build the code base
3. Use the understanding to buid application for Influencer Marketing Analytics.

Corpus Creation
1. Current corpus creation is from Amazon Electronics Reviews


Future Work
1. Speech to Text from Top N (N=5) youtube india influencers.

# Corpus

In [1]:
import pandas as pd
import numpy as np

import nltk
nltk.download('punkt')

from time import sleep
from tqdm import tqdm
import string

from keras.preprocessing.text import Tokenizer

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


In [2]:
#----JSON Path
electronics_path = "https://www.cs.odu.edu/~hpendyal/courses/cs620/project/dataset/Electronics_5.json"

#---- Reading Electronics data
print('-> Started Loading Data')
Electronics = pd.read_json(electronics_path, lines=True)
print('-> Total reviews : ',Electronics.reviewText.count())
print("Data Loading completed in ")

#----Check Data
Electronics.head()

-> Started Loading Data
-> Total reviews :  1689188
Data Loading completed in 


reviewerID        asin  ... unixReviewTime   reviewTime
0   AO94DHGC771SJ  0528881469  ...     1370131200   06 2, 2013
1   AMO214LNFCEI4  0528881469  ...     1290643200  11 25, 2010
2  A3N7T0DY83Y4IG  0528881469  ...     1283990400   09 9, 2010
3  A1H8PY3QHMQQA0  0528881469  ...     1290556800  11 24, 2010
4  A24EV6RXELQZ63  0528881469  ...     1317254400  09 29, 2011

[5 rows x 9 columns]

In [3]:
def clean_text(txt):
    txt = "".join(v for v in txt if v not in string.punctuation).lower()
    txt = txt.encode("utf8").decode("ascii",'ignore')
    return txt 

In [4]:
#---- Creating Corpus
n=100
# Step 1 - Breaking each review in sentences.
# Step 2 - Appending sentences to create a list of senteneces i.e. Corpus
corpus =[]
for review in tqdm(Electronics['reviewText'][:n]):
  #review = clean_text(review)
  sent_text = nltk.sent_tokenize(review)
  #print(sent_text)
  corpus = corpus + [clean_text(text) for text in sent_text]
  #corpus = corpus + sent_text
  sleep(5)
print('-> Total length of sentences', len(corpus))

100%|██████████| 100/100 [08:20<00:00,  5.01s/it]

-> Total lenngth of sentences 515


In [ ]:
#----Check Corpus
corpus[:10]

['we got this gps for my husband who is an otr over the road trucker',
 'very impressed with the shipping time it arrived a few days earlier than expected  within a week of use however it started freezing up could of just been a glitch in that unit',
 'worked great when it worked',
 'will work great for the normal person as well but does have the trucker option',
 'the big truck routes  tells you when a scale is coming up ect  love the bigger screen the ease of use the ease of putting addresses into memory',
 'nothing really bad to say about the unit with the exception of it freezing which is probably one in a million and thats just my luck',
 'i contacted the seller and within minutes of my email i received a email back with instructions for an exchange',
 'very impressed all the way around',
 'im a professional otr truck driver and i bought a tnd 700 at a truck stop hoping to make my life easier',
 'rand mcnally are you listeningfirst thing i did after charging it was connect it to m

In [5]:
tokenizer = Tokenizer()

def get_sequence_of_tokens(corpus):
    ## tokenization
    tokenizer.fit_on_texts(corpus)
    total_words = len(tokenizer.word_index) + 1
    
    ## convert data to sequence of tokens 
    input_sequences = []
    for line in tqdm(corpus):
        token_list = tokenizer.texts_to_sequences([line])[0]
        for i in range(1, len(token_list)):
            n_gram_sequence = token_list[:i+1]
            input_sequences.append(n_gram_sequence)
        sleep(5)
    return input_sequences, total_words

inp_sequences, total_words = get_sequence_of_tokens(corpus[:10])
inp_sequences[:10]

100%|██████████| 10/10 [00:50<00:00,  5.01s/it]


[[31, 32],
 [31, 32, 33],
 [31, 32, 33, 34],
 [31, 32, 33, 34, 9],
 [31, 32, 33, 34, 9, 5],
 [31, 32, 33, 34, 9, 5, 35],
 [31, 32, 33, 34, 9, 5, 35, 36],
 [31, 32, 33, 34, 9, 5, 35, 36, 10],
 [31, 32, 33, 34, 9, 5, 35, 36, 10, 13],
 [31, 32, 33, 34, 9, 5, 35, 36, 10, 13, 14]]

In [7]:
tokenizer.texts_to_sequences(['I love you'])

[[8, 70, 28]]

# Tutorial
1. Word Embedding

In [46]:
def get_sequence_of_tokens(corpus):
    ## tokenization
    tokenizer.fit_on_texts(corpus)
    total_words = len(tokenizer.word_index) + 1
    ## convert data to sequence of tokens 
    input_sequences = []
    for line in tqdm(corpus):
        input_sequences = input_sequences + (tokenizer.texts_to_sequences([line]))
        sleep(5)
    return input_sequences, total_words

inp_sequences, total_words = get_sequence_of_tokens(corpus[:10])
inp_sequences[:10]

100%|██████████| 10/10 [00:50<00:00,  5.01s/it]


[[31, 32, 33, 34, 9, 5, 35, 36, 10, 13, 14, 37, 1, 38, 15],
 [16,
  17,
  11,
  1,
  39,
  40,
  3,
  41,
  2,
  42,
  43,
  44,
  45,
  46,
  18,
  2,
  47,
  4,
  19,
  48,
  3,
  49,
  20,
  21,
  50,
  4,
  22,
  51,
  2,
  52,
  23,
  53,
  24],
 [25, 26, 27, 3, 25],
 [54, 55, 26, 9, 1, 56, 57, 58, 59, 60, 61, 62, 1, 15, 63],
 [1,
  64,
  12,
  65,
  66,
  28,
  27,
  2,
  67,
  10,
  68,
  21,
  69,
  70,
  1,
  71,
  72,
  1,
  29,
  4,
  19,
  1,
  29,
  4,
  73,
  74,
  75,
  76],
 [77,
  78,
  79,
  7,
  80,
  81,
  1,
  24,
  11,
  1,
  82,
  4,
  3,
  20,
  83,
  10,
  84,
  85,
  23,
  2,
  86,
  6,
  87,
  22,
  5,
  88],
 [8, 89, 1, 90, 6, 18, 91, 4, 5, 30, 8, 92, 2, 30, 93, 11, 94, 9, 13, 95],
 [16, 17, 96, 1, 97, 98],
 [99,
  2,
  100,
  14,
  12,
  101,
  6,
  8,
  102,
  2,
  103,
  104,
  105,
  2,
  12,
  106,
  107,
  7,
  108,
  5,
  109,
  110],
 [111,
  112,
  113,
  28,
  114,
  115,
  8,
  116,
  117,
  118,
  3,
  119,
  120,
  3,
  7,
  5,
  121,
  6,
  122

In [48]:
#Padding Text squeence
import tensorflow as tf
inp_sequences = tf.keras.preprocessing.sequence.pad_sequences(
    inp_sequences, maxlen=27, dtype='int32', padding='pre', truncating='pre',
    value=0.0
)

In [49]:
inp_sequences

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  31,
         32,  33,  34,   9,   5,  35,  36,  10,  13,  14,  37,   1,  38,
         15],
       [  3,  41,   2,  42,  43,  44,  45,  46,  18,   2,  47,   4,  19,
         48,   3,  49,  20,  21,  50,   4,  22,  51,   2,  52,  23,  53,
         24],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,  25,  26,  27,   3,
         25],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  54,
         55,  26,   9,   1,  56,  57,  58,  59,  60,  61,  62,   1,  15,
         63],
       [ 64,  12,  65,  66,  28,  27,   2,  67,  10,  68,  21,  69,  70,
          1,  71,  72,   1,  29,   4,  19,   1,  29,   4,  73,  74,  75,
         76],
       [  0,  77,  78,  79,   7,  80,  81,   1,  24,  11,   1,  82,   4,
          3,  20,  83,  10,  84,  85,  23,   2,  86,   6,  87,  22,   5,
         88],
       [  0,   0,   0,   0,   0,   0,   

In [62]:
inp_sequences[6:10]

array([[  0,   0,   0,   0,   0,   0,   0,   8,  89,   1,  90,   6,  18,
         91,   4,   5,  30,   8,  92,   2,  30,  93,  11,  94,   9,  13,
         95],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,  16,  17,  96,   1,  97,
         98],
       [  0,   0,   0,   0,   0,  99,   2, 100,  14,  12, 101,   6,   8,
        102,   2, 103, 104, 105,   2,  12, 106, 107,   7, 108,   5, 109,
        110],
       [111, 112, 113,  28, 114, 115,   8, 116, 117, 118,   3, 119, 120,
          3,   7,   5, 121,   6, 122,   1, 123,   6, 124, 125,   7, 126,
          3]], dtype=int32)

In [63]:
inp_sequences[0:5]

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 31, 32, 33, 34,
         9,  5, 35, 36, 10, 13, 14, 37,  1, 38, 15],
       [ 3, 41,  2, 42, 43, 44, 45, 46, 18,  2, 47,  4, 19, 48,  3, 49,
        20, 21, 50,  4, 22, 51,  2, 52, 23, 53, 24],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0,  0, 25, 26, 27,  3, 25],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 54, 55, 26,  9,
         1, 56, 57, 58, 59, 60, 61, 62,  1, 15, 63],
       [64, 12, 65, 66, 28, 27,  2, 67, 10, 68, 21, 69, 70,  1, 71, 72,
         1, 29,  4, 19,  1, 29,  4, 73, 74, 75, 76]], dtype=int32)

In [54]:
total_words

127

In [55]:
#Declaring word embedding layer
from tensorflow.keras.layers import Activation, Dense, Embedding, GlobalAveragePooling1D, Flatten
embedding = Embedding(total_words, 100, input_length=inp_sequences.shape[1])

In [56]:
#Creating sequential model
from tensorflow.keras import Model, Sequential
model = Sequential()
model.add(embedding)
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

model.compile(
    optimizer="adam",
    loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
    metrics=["accuracy"],
)

In [57]:
model.summary()

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, 27, 100)           12700     
_________________________________________________________________
flatten_6 (Flatten)          (None, 2700)              0         
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 2701      
Total params: 15,401
Trainable params: 15,401
Non-trainable params: 0
_________________________________________________________________


In [64]:
history = model.fit(
    inp_sequences[6:10], epochs=1, validation_steps=20, validation_data=inp_sequences[0:5]
)

ValueError: ignored

2. Named Entity Recognition

3. RNN

4. LSTM

# Social Media Influencer Analytics
# Objective 1 - Unstructured Data to Structured Data
1. Convert speech to text. - 
a. converting sound to txt
b. Entity Recognition for tagging
2. Convert images to objects - Time in seconds an object is displayed in the video
3. Positive/Negative Reviews - Entity Recognition

#Objective 2 -Club data with youtube impressions data